// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '126TH U.S. OPEN',
  title: 'U.S. OPEN PICK 3 LIVE',
  venue: 'Shinnecock Hills Golf Club',
  location: 'Southampton, New York',
  dates: 'June 18–21, 2026',
  prizePool: '$3,625',
  tournamentTimezone: 'America/New_York',
  jackpotRule: 'To win, your picks must include the U.S. Open Champion. If no punter selects them, the prize pool jackpots again.',
  heroImage: 'https://images.unsplash.com/photo-1500932334442-8761ee4810a7?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Xander Schauffele', 'Rory McIlroy', 'Tommy Fleetwood'] },
  { player: 'Enright', picks: ['Wyndham Clark', 'Rory McIlroy', 'Scottie Scheffler'] },
  { player: 'Roche SES', picks: ['Matt Fitzpatrick', 'Rory McIlroy', 'Tommy Fleetwood'] },
  { player: 'Kitch', picks: ['Scottie Scheffler', 'Cameron Young', 'Russell Henley'] },
  { player: 'Brom', picks: ['Matt Fitzpatrick', 'Wyndham Clark', 'Tommy Fleetwood'] },
  { player: 'Shaw', picks: ['Patrick Reed', 'Xander Schauffele', 'Cameron Smith'] },
  { player: 'Brian Irish', picks: ['Xander Schauffele', 'Sam Burns', 'Bryson DeChambeau'] },
  { player: 'Jonesy', picks: ['Robert MacIntyre', 'Rory McIlroy', 'Scottie Scheffler'] },
  { player: 'Haycock Snr', picks: ['Rory McIlroy', 'Kristoffer Reitan', 'Ryan Fox'] },
  { player: 'Mal J', picks: ['Russell Henley', 'Tommy Fleetwood', 'Ludvig Åberg'] },
  { player: 'Doc Campbell', picks: ['Jon Rahm', 'Scottie Scheffler', 'Rory McIlroy'] },
  { player: 'T Coleman', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Cameron Young'] },
  { player: 'A Rose', picks: ['Scottie Scheffler', 'J.J. Spaun', 'Russell Henley'] },
  { player: 'D Haycock', picks: ['Scottie Scheffler', 'Patrick Reed', 'Tommy Fleetwood'] },
  { player: 'P Langley', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Scottie Scheffler'] },
  { player: 'T Wallace', picks: ['Matt Fitzpatrick', 'Ludvig Åberg', 'Tommy Fleetwood'] },
  { player: 'K Ferg', picks: ['Matt Fitzpatrick', 'Wyndham Clark', 'Brooks Koepka'] },
  { player: 'JB', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Jon Rahm'] },
  { player: 'D McCarthy', picks: ['Xander Schauffele', 'Jon Rahm', 'Si Woo Kim'] },
  { player: 'Nath Ferg', picks: ['Cameron Young', 'Sepp Straka', 'Xander Schauffele'] },
  { player: 'Muzza T', picks: ['Emiliano Grillo', 'Ryan Fox', 'Rory McIlroy'] },
  { player: 'D Donnelly', picks: ['Russell Henley', 'Chris Gotterup', 'Matt Fitzpatrick'] },
  { player: 'Hancock', picks: ['Jackson Koivun', 'Tommy Fleetwood', 'Tyrrell Hatton'] },
  { player: 'B Ashford', picks: ['Matt Fitzpatrick', 'Tommy Fleetwood', 'Russell Henley'] },
  { player: 'Bradley C', picks: ['Cameron Young', 'Justin Thomas', 'Scottie Scheffler'] },
  { player: 'Sloanie', picks: ['Jon Rahm', 'Scottie Scheffler', 'Rory McIlroy'] },
  { player: 'R Fowler', picks: ['Cameron Young', 'Tommy Fleetwood', 'Wyndham Clark'] },
  { player: 'Sparky', picks: ['Ludvig Åberg', 'Ryan Fox', 'Tommy Fleetwood'] },
  { player: 'Barley', picks: ['Tommy Fleetwood', 'Patrick Reed', 'Ludvig Åberg'] },
  { player: 'Pete Holly', picks: ['Sam Burns', 'Viktor Hovland', 'Wyndham Clark'] },
  { player: 'Timmy S', picks: ['Tommy Fleetwood', 'Collin Morikawa', 'Matt Fitzpatrick'] },
  { player: 'Mr Grant', picks: ['Rory McIlroy', 'Scottie Scheffler', 'Matt Fitzpatrick'] },
  { player: 'Greg B', picks: ['Ludvig Åberg', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'JD Boy', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Brooks Koepka'] },
  { player: 'Mr Manson', picks: ['Cameron Young', 'Ludvig Åberg', 'Scottie Scheffler'] },
  { player: 'Up the Wahs', picks: ['Rory McIlroy', 'Sam Burns', 'J.J. Spaun'] },
  { player: 'G Ponting', picks: ['Brooks Koepka', 'Sam Burns', 'J.J. Spaun'] },
  { player: 'R McKnight', picks: ['Scottie Scheffler', 'Sam Burns', 'Rory McIlroy'] },
  { player: 'Chalkey', picks: ['Tommy Fleetwood', 'Jon Rahm', 'Cameron Young'] },
  { player: 'Budgie', picks: ['Jon Rahm', 'J.J. Spaun', 'Wyndham Clark'] },
  { player: 'Lamming', picks: ['Rory McIlroy', 'Collin Morikawa', 'Ludvig Åberg'] },
  { player: 'A Bull', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Wyndham Clark'] },
  { player: 'Lynda R', picks: ['Matt Fitzpatrick', 'Wyndham Clark', 'Viktor Hovland'] },
  { player: 'Cam P', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Wyndham Clark'] },
  { player: 'Wazza SB', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Cameron Young'] },
  { player: 'Mac The Knife', picks: ['Kristoffer Reitan', 'Cameron Young', 'Kurt Kitayama'] },
  { player: 'Crusader', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Matt Fitzpatrick'] },
  { player: 'Maccas', picks: ['Collin Morikawa', 'Russell Henley', 'Patrick Cantlay'] },
  { player: 'Matt B', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Jon Rahm'] },
  { player: 'The Wrangler', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Tommy Fleetwood'] },
  { player: 'AD', picks: ['Tommy Fleetwood', 'Matt Fitzpatrick', 'Xander Schauffele'] },
  { player: 'J Turner', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Tyrrell Hatton'] },
  { player: 'M Sanders', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Justin Rose'] },
  { player: 'Nick Fitz', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Min Woo Lee'] },
  { player: 'T Rowe', picks: ['Ludvig Åberg', 'Cameron Young', 'Scottie Scheffler'] },
  { player: 'J Tilley', picks: ['Matt Fitzpatrick', 'Jon Rahm', 'Russell Henley'] },
  { player: 'Arnie Palmer', picks: ['Scottie Scheffler', 'Cameron Young', 'Tommy Fleetwood'] },
  { player: 'Kimbo Slice', picks: ['Scottie Scheffler', 'Russell Henley', 'Tommy Fleetwood'] },
  { player: 'L Adams', picks: ['Bryson DeChambeau', 'Jon Rahm', 'Rory McIlroy'] },
  { player: 'K McGinness', picks: ['Sam Burns', 'Matt Fitzpatrick', 'Tommy Fleetwood'] },
  { player: 'Baylis', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Justin Rose'] },
  { player: 'D Tucker', picks: ['Scottie Scheffler', 'Tyrrell Hatton', 'Jon Rahm'] },
  { player: 'Kev Martin', picks: ['Ludvig Åberg', 'Rory McIlroy', 'Corey Conners'] },
  { player: 'P Mac', picks: ['Scottie Scheffler', 'Cameron Young', 'Tommy Fleetwood'] },
  { player: 'J Barbour', picks: ['Scottie Scheffler', 'Wyndham Clark', 'Russell Henley'] },
  { player: 'P Lund', picks: ['Russell Henley', 'Tyrrell Hatton', 'Sam Burns'] },
  { player: 'Trump H', picks: ['Kristoffer Reitan', 'Viktor Hovland', 'Scottie Scheffler'] },
  { player: 'John Edge', picks: ['Tommy Fleetwood', 'Ludvig Åberg', 'Xander Schauffele'] },
  { player: 'Trent W', picks: ['Justin Thomas', 'Xander Schauffele', 'Rory McIlroy'] },
  { player: 'Sir Steve', picks: ['Jon Rahm', 'Xander Schauffele', 'Matt Fitzpatrick'] },
  { player: 'Nat M', picks: ['Cameron Young', 'Jon Rahm', 'Scottie Scheffler'] },
  { player: 'Spinetto', picks: ['Xander Schauffele', 'Tommy Fleetwood', 'Matt Fitzpatrick'] }
];
