// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '126TH U.S. OPEN',
  title: 'U.S. OPEN PICK 3 LIVE',
  venue: 'Shinnecock Hills Golf Club',
  location: 'Southampton, New York',
  dates: 'June 18–21, 2026',
  prizePool: '$3,500',
  tournamentTimezone: 'America/New_York',
  jackpotRule: 'To win, your picks must include the U.S. Open Champion. If no punter selects them, the prize pool jackpots again.',
  heroImage: 'https://images.unsplash.com/photo-1500932334442-8761ee4810a7?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Xander Schauffele'] },
  { player: 'Enright', picks: ['Scottie Scheffler', 'Ludvig Aberg', 'Patrick Cantlay'] },
  { player: 'Roche SES', picks: ['Rory McIlroy', 'Tommy Fleetwood', 'Russell Henley'] },
  { player: 'Kitch', picks: ['Xander Schauffele', 'Robert MacIntyre', 'Rickie Fowler'] },
  { player: 'Brom', picks: ['Scottie Scheffler', 'Min Woo Lee', 'Sam Burns'] },
  { player: 'Shaw', picks: ['Rory McIlroy', 'Jordan Spieth', 'Ben Griffin'] },
  { player: 'Brian Irish', picks: ['Ludvig Aberg', 'Hideki Matsuyama', 'Justin Thomas'] },
  { player: 'Jonesy', picks: ['Scottie Scheffler', 'Patrick Cantlay', 'Tommy Fleetwood'] },
  { player: 'Haycock Snr', picks: ['Xander Schauffele', 'Russell Henley', 'Si Woo Kim'] },
  { player: 'Mal J', picks: ['Rory McIlroy', 'Cameron Young', 'Matt Fitzpatrick'] },

  { player: 'Doc Campbell', picks: ['Scottie Scheffler', 'Robert MacIntyre', 'Akshay Bhatia'] },
  { player: 'T Coleman', picks: ['Ludvig Aberg', 'Rickie Fowler', 'Jason Day'] },
  { player: 'A Rose', picks: ['Rory McIlroy', 'Ben Griffin', 'J.J. Spaun'] },
  { player: 'D Haycock', picks: ['Xander Schauffele', 'Justin Rose', 'Sepp Straka'] },
  { player: 'P Langley', picks: ['Scottie Scheffler', 'Justin Thomas', 'Corey Conners'] },
  { player: 'T Wallace', picks: ['Patrick Cantlay', 'Hideki Matsuyama', 'Sam Burns'] },
  { player: 'K Ferg', picks: ['Rory McIlroy', 'Tommy Fleetwood', 'Min Woo Lee'] },
  { player: 'JB', picks: ['Scottie Scheffler', 'Jordan Spieth', 'Gary Woodland'] },
  { player: 'D McCarthy', picks: ['Ludvig Aberg', 'Russell Henley', 'Maverick McNealy'] },
  { player: 'Nath Ferg', picks: ['Xander Schauffele', 'Matt Fitzpatrick', 'Chris Gotterup'] },

  { player: 'Muzza T', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Ben Griffin'] },
  { player: 'D Donnelly', picks: ['Rory McIlroy', 'Patrick Cantlay', 'Hideki Matsuyama'] },
  { player: 'Hancock', picks: ['Ludvig Aberg', 'Robert MacIntyre', 'Justin Thomas'] },
  { player: 'B Ashford', picks: ['Xander Schauffele', 'Rickie Fowler', 'Sam Burns'] },
  { player: 'Bradley C', picks: ['Scottie Scheffler', 'Russell Henley', 'Jordan Spieth'] },
  { player: 'Sloanie', picks: ['Rory McIlroy', 'Min Woo Lee', 'Akshay Bhatia'] },
  { player: 'R Fowler', picks: ['Patrick Cantlay', 'Rickie Fowler', 'Tony Finau'] },
  { player: 'Sparky', picks: ['Scottie Scheffler', 'Justin Thomas', 'Brian Harman'] },
  { player: 'Barley', picks: ['Ludvig Aberg', 'Tommy Fleetwood', 'Sahith Theegala'] },
  { player: 'Pete Holly', picks: ['Xander Schauffele', 'Hideki Matsuyama', 'J.T. Poston'] },

  { player: 'Timmy S', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Patrick Cantlay'] },
  { player: 'Mr Grant', picks: ['Ludvig Aberg', 'Ben Griffin', 'Russell Henley'] },
  { player: 'Greg B', picks: ['Xander Schauffele', 'Robert MacIntyre', 'Jordan Spieth'] },
  { player: 'JD Boy', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Rickie Fowler'] },
  { player: 'Mr Manson', picks: ['Rory McIlroy', 'Justin Thomas', 'Sam Burns'] },
  { player: 'G Ponting', picks: ['Ludvig Aberg', 'Matt Fitzpatrick', 'Jason Day'] },
  { player: 'R McKnight', picks: ['Scottie Scheffler', 'Min Woo Lee', 'Hideki Matsuyama'] },
  { player: 'Chalkey', picks: ['Xander Schauffele', 'Russell Henley', 'Ben Griffin'] },
  { player: 'Budgie', picks: ['Rory McIlroy', 'Patrick Cantlay', 'Sepp Straka'] },
  { player: 'Lamming', picks: ['Scottie Scheffler', 'Jordan Spieth', 'Akshay Bhatia'] },

  { player: 'A Bull', picks: ['Ludvig Aberg', 'Tommy Fleetwood', 'Justin Rose'] },
  { player: 'Lynda R', picks: ['Rory McIlroy', 'Rickie Fowler', 'Corey Conners'] },
  { player: 'Cam P', picks: ['Xander Schauffele', 'Justin Thomas', 'Maverick McNealy'] },
  { player: 'Wazza SB', picks: ['Scottie Scheffler', 'Sam Burns', 'Matt Fitzpatrick'] },
  { player: 'Mac The Knife', picks: ['Patrick Cantlay', 'Hideki Matsuyama', 'Ben Griffin'] },
  { player: 'Crusader', picks: ['Rory McIlroy', 'Russell Henley', 'Robert MacIntyre'] },
  { player: 'Maccas', picks: ['Ludvig Aberg', 'Min Woo Lee', 'Jordan Spieth'] },
  { player: 'Matt B', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Tommy Fleetwood'] },
  { player: 'The Wrangler', picks: ['Rory McIlroy', 'Justin Thomas', 'Rickie Fowler'] },
  { player: 'AD', picks: ['Patrick Cantlay', 'Sam Burns', 'Akshay Bhatia'] },

  { player: 'J Turner', picks: ['Scottie Scheffler', 'Ben Griffin', 'Jason Day'] },
  { player: 'M Sanders', picks: ['Ludvig Aberg', 'Russell Henley', 'Hideki Matsuyama'] },
  { player: 'Nick Fitz', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Tommy Fleetwood'] },
  { player: 'M Little', picks: ['Xander Schauffele', 'Min Woo Lee', 'Justin Thomas'] },
  { player: 'T Rowe', picks: ['Scottie Scheffler', 'Jordan Spieth', 'Robert MacIntyre'] },
  { player: 'J Tilley', picks: ['Rory McIlroy', 'Patrick Cantlay', 'Ben Griffin'] },
  { player: 'Arnie Palmer', picks: ['Ludvig Aberg', 'Rickie Fowler', 'Sam Burns'] },
  { player: 'K. Sanders', picks: ['Scottie Scheffler', 'Hideki Matsuyama', 'Akshay Bhatia'] },
  { player: 'L Adams', picks: ['Xander Schauffele', 'Russell Henley', 'Sepp Straka'] },
  { player: 'K McGinness', picks: ['Rory McIlroy', 'Justin Rose', 'Corey Conners'] },

  { player: 'Baylis', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Justin Thomas'] },
  { player: 'D Tucker', picks: ['Ludvig Aberg', 'Patrick Cantlay', 'Jordan Spieth'] },
  { player: 'Kev Martin', picks: ['Rory McIlroy', 'Ben Griffin', 'Hideki Matsuyama'] },
  { player: 'P Mac', picks: ['Xander Schauffele', 'Rickie Fowler', 'Min Woo Lee'] },
  { player: 'J Barbour', picks: ['Scottie Scheffler', 'Russell Henley', 'Sam Burns'] },
  { player: 'P Lund', picks: ['Rory McIlroy', 'Tommy Fleetwood', 'Akshay Bhatia'] },
  { player: 'Trump H', picks: ['Ludvig Aberg', 'Justin Thomas', 'Robert MacIntyre'] },
  { player: 'John Edge', picks: ['Scottie Scheffler', 'Patrick Cantlay', 'Matt Fitzpatrick'] },
  { player: 'Trent W', picks: ['Xander Schauffele', 'Jordan Spieth', 'Ben Griffin'] },
  { player: 'Sir Steve', picks: ['Rory McIlroy', 'Hideki Matsuyama', 'Russell Henley'] }
];
