// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '154TH OPEN CHAMPIONSHIP',
  title: 'THE OPEN PICK 3 LIVE',
  venue: 'Royal Birkdale Golf Club',
  location: 'Southport, Merseyside, England',
  dates: 'July 16–19, 2026',
  prizePool: '$1,875',
  tournamentTimezone: 'Europe/London',
  jackpotRule: 'To win, your picks must include the Champion Golfer of the Year. If no punter selects them, the prize pool jackpots.',
  heroImage: 'https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Rory McIlroy', 'Scottie Scheffler', 'Xander Schauffele'] },
  { player: 'Enright', picks: ['Scottie Scheffler', 'Wyndham Clark', 'Chris Gotterup'] },
  { player: 'Roche SES', picks: ['Rory McIlroy', 'Tommy Fleetwood', 'Cameron Young'] },
  { player: 'Kitch', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Tom Kim'] },
  { player: 'Brom', picks: ['Matt Fitzpatrick', 'Chris Gotterup', 'Rory McIlroy'] },
  { player: 'Shaw', picks: ['Ben Griffin', 'Patrick Reed', 'Xander Schauffele'] },
  { player: 'Brian Irish', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Tom Kim'] },
  { player: 'Jonesy', picks: ['Rory McIlroy', 'Robert MacIntyre', 'Tommy Fleetwood'] },
  { player: 'Haycock Snr', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Ludvig Åberg'] },
  { player: 'Mal J', picks: ['Robert MacIntyre', 'Matt Fitzpatrick', 'Chris Gotterup'] },

  { player: 'Doc Campbell', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Wyndham Clark'] },
  { player: 'T Coleman', picks: ['Viktor Hovland', 'Scottie Scheffler', 'Tommy Fleetwood'] },
  { player: 'A Rose', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Tyrrell Hatton'] },
  { player: 'D Haycock', picks: ['Chris Gotterup', 'Tyrrell Hatton', 'Patrick Reed'] },
  { player: 'P Langley', picks: ['Matt Fitzpatrick', 'Rory McIlroy', 'Robert MacIntyre'] },
  { player: 'T Wallace', picks: ['Matt Fitzpatrick', 'Tommy Fleetwood', 'Tyrrell Hatton'] },
  { player: 'K Ferg', picks: ['Matt Fitzpatrick', 'Viktor Hovland', 'Tyrrell Hatton'] },
  { player: 'JB', picks: ['Rory McIlroy', 'Xander Schauffele', 'Tommy Fleetwood'] },
  { player: 'D McCarthy', picks: ['Matt Fitzpatrick', 'Robert MacIntyre', 'Viktor Hovland'] },
  { player: 'Nath Ferg', picks: ['Matt Fitzpatrick', 'Cameron Young', 'Justin Rose'] },

  { player: 'Muzza T', picks: ['Tom Kim', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'D Donnelly', picks: ['Wyndham Clark', 'Justin Rose', 'Russell Henley'] },
  { player: 'Hancock', picks: ['Tommy Fleetwood', 'Tyrrell Hatton', 'Justin Rose'] },
  { player: 'B Ashford', picks: ['Tommy Fleetwood', 'Matt Fitzpatrick', 'Tyrrell Hatton'] },
  { player: 'Bradley C', picks: ['Keegan Bradley', 'Adam Scott', 'Justin Thomas'] },

    { player: 'Sloanie', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Tyrrell Hatton'] },
  { player: 'R Fowler', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Chris Gotterup'] },
  { player: 'Sparky', picks: ['Rory McIlroy', 'Ryan Fox', 'Tommy Fleetwood'] },
  { player: 'Barley', picks: ['Tyrrell Hatton', 'Tommy Fleetwood', 'Nicolai Højgaard'] },
  { player: 'Pete Holly', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'Timmy S', picks: ['Tommy Fleetwood', 'Aaron Rai', 'Rory McIlroy'] },
  { player: 'Mr Grant', picks: ['Scottie Scheffler', 'Matt Fitzpatrick', 'Xander Schauffele'] },
  { player: 'Greg B', picks: ['Ludvig Åberg', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'JD Boy', picks: ['Scottie Scheffler', 'Jon Rahm', 'Xander Schauffele'] },
  { player: 'Mr Manson', picks: ['Tom Kim', 'Robert MacIntyre', 'Matt Fitzpatrick'] },

  { player: 'Up the Whas', picks: ['Rory McIlroy', 'Xander Schauffele', 'Chris Gotterup'] },
  { player: 'G Ponting', picks: ['Tyrrell Hatton', 'Jon Rahm', 'Tommy Fleetwood'] },
  { player: 'R McKnight', picks: ['Joaquin Niemann', 'Matt Fitzpatrick', 'Robert MacIntyre'] },
  { player: 'Chalkey', picks: ['Rory McIlroy', 'Robert MacIntyre', 'Tommy Fleetwood'] },
  { player: 'Budgie', picks: ['Rory McIlroy', 'Collin Morikawa', 'Matt Fitzpatrick'] },
  { player: 'Lamming', picks: ['Rory McIlroy', 'Shane Lowry', 'Joaquin Niemann'] },
  { player: 'A Bull', picks: ['Wyndham Clark', 'Robert MacIntyre', 'Rory McIlroy'] },
  { player: 'Lynda R', picks: ['Matt Fitzpatrick', 'Justin Rose', 'Xander Schauffele'] },
  { player: 'Cam P', picks: ['Matt Fitzpatrick', 'Scottie Scheffler', 'Sam Burns'] },
  { player: 'Mac The Knife', picks: ['Kristoffer Reitan', 'Cameron Young', 'Keita Nakajima'] },

  { player: 'Crusader', picks: ['Scottie Scheffler', 'Matt Fitzpatrick', 'Tommy Fleetwood'] },
  { player: 'Maccas', picks: ['Collin Morikawa', 'Viktor Hovland', 'Eugenio Chacarra'] },
  { player: 'Matt B', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Jon Rahm'] },
  { player: 'The Wrangler', picks: ['Scottie Scheffler', 'Xander Schauffele', 'Robert MacIntyre'] },
  { player: 'AD', picks: ['Rory McIlroy', 'Min Woo Lee', 'Matt Fitzpatrick'] },

    { player: 'J Turner', picks: ['Scottie Scheffler', 'Sam Burns', 'Ludvig Åberg'] },
  { player: 'M Sanders', picks: ['Matt Fitzpatrick', 'Russell Henley', 'Robert MacIntyre'] },
  { player: 'Nick Fitz', picks: ['Matt Fitzpatrick', 'Ludvig Åberg', 'Justin Thomas'] },
  { player: 'T Rowe', picks: ['Justin Rose', 'Tyrrell Hatton', 'Shane Lowry'] },
  { player: 'J Tilley', picks: ['Robert MacIntyre', 'Scottie Scheffler', 'Rory McIlroy'] },
  { player: 'Arnie Palmer', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Justin Rose'] },
  { player: 'Kimbo Slice', picks: ['Patrick Reed', 'Scottie Scheffler', 'Matt Fitzpatrick'] },
  { player: 'L Adams', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Collin Morikawa'] },
  { player: 'K McGinness', picks: ['Matt Fitzpatrick', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'Baylis', picks: ['Scottie Scheffler', 'Tommy Fleetwood', 'Justin Rose'] },

  { player: 'D Tucker', picks: ['Rory McIlroy', 'Matt Fitzpatrick', 'Robert MacIntyre'] },
  { player: 'Kev Martin', picks: ['Ludvig Åberg', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'P Mac', picks: ['Rory McIlroy', 'Scottie Scheffler', 'Collin Morikawa'] },
  { player: 'P Lund', picks: ['Tyrrell Hatton', 'Russell Henley', 'Brian Harman'] },
  { player: 'Trump H', picks: ['Scottie Scheffler', 'Shane Lowry', 'Padraig Harrington'] },
  { player: 'John Edge', picks: ['Tom Kim', 'Collin Morikawa', 'Justin Rose'] },
  { player: 'Trent W', picks: ['Matt Fitzpatrick', 'Tommy Fleetwood', 'Rory McIlroy'] },
  { player: 'Nat M', picks: ['Scottie Scheffler', 'Matt Fitzpatrick', 'Tyrrell Hatton'] },
  { player: 'Spinetto', picks: ['Scottie Scheffler', 'Rory McIlroy', 'Brooks Koepka'] },
  { player: 'Katie D', picks: ['Xander Schauffele', 'Tommy Fleetwood', 'Chris Gotterup'] },

  { player: 'H Naka', picks: ['Akshay Bhatia', 'Tommy Fleetwood', 'Cameron Young'] },
  { player: 'M Little', picks: ['Matt Fitzpatrick', 'Cameron Young', 'Rory McIlroy'] },
  { player: 'Wazza SB', picks: ['Rory McIlroy', 'Scottie Scheffler', 'Matt Fitzpatrick'] },
  { player: 'Sir Steve', picks: ['Matt Fitzpatrick', 'Rory McIlroy', 'Scottie Scheffler'] },
  { player: 'J Barbour', picks: ['Matt Fitzpatrick', 'Tommy Fleetwood', 'Justin Rose'] },
];
